"""Pydantic request/response schemas."""

from app.models.schemas import (
    BacktestRequest,
    BacktestResponse,
    BenchmarkComparison,
    EfficientFrontierRequest,
    EfficientFrontierResponse,
    ForecastRequest,
    ForecastResponse,
    FrontierPoint,
    HoldingInput,
    MetricsRequest,
    MetricsResponse,
    MonteCarloRequest,
    MonteCarloResponse,
    NewsItem,
    PortfolioMetrics,
    PricePoint,
    SectorExposure,
    ShareMetric,
    StockForecast,
)

__all__ = [
    "BacktestRequest",
    "BacktestResponse",
    "BenchmarkComparison",
    "EfficientFrontierRequest",
    "EfficientFrontierResponse",
    "ForecastRequest",
    "ForecastResponse",
    "FrontierPoint",
    "HoldingInput",
    "MetricsRequest",
    "MetricsResponse",
    "MonteCarloRequest",
    "MonteCarloResponse",
    "NewsItem",
    "PortfolioMetrics",
    "PricePoint",
    "SectorExposure",
    "ShareMetric",
    "StockForecast",
]
